# For more information about the available options please visit: http://go/catalog-info (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/UnityContentBuildExamples
  name: UnityContentBuildExamples
  description: "Small example projects related to building content with Unity, for example 'content directory' builds."
  labels:
    costcenter: "5022"
  tags:
    - planned-public
    - enterprise
spec:
  type: documentation
  lifecycle: production
  owner: Unity-Technologies/content-build-load
